name: CI
on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Calculate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        targetPath: EncompassApi.xUnit
        useConfigFile: true
        updateAssemblyInfo: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Restore NuGet Packages
      run: dotnet restore EncompassApi.xUnit/EncompassApi.xUnit.csproj

    - name: Build Solution
      run: dotnet build -c $env:CONFIGURATION -p:Version=${{ steps.gitversion.outputs.MajorMinorPatch }} -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }} --version-suffix ${{ steps.gitversion.outputs.PreReleaseTag }} EncompassApi.xUnit/EncompassApi.xUnit.csproj

    - name: Run Tests
      run: dotnet test EncompassApi.xUnit.Sample/EncompassApi.xUnit.Sample.csproj --logger "trx;LogFileName=test-results.trx" --results-directory TestResults
      continue-on-error: true

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: 'TestResults/*.trx'
