name: Publish
on:
  workflow_run:
    workflows: ['CI']
    branches:
      - master
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
      
    variables:
      version.MajorMinor: '1.2' # Manually adjust the version number as needed for semantic versioning. Revision is auto-incremented.
      version.Revision: $[counter(variables['version.MajorMinor'], 0)]
      versionNumber: '$(version.MajorMinor).$(version.Revision)'
  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Calculate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        targetPath: EncompassApi.xUnit
        useConfigFile: true
        updateAssemblyInfo: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    - name: Restore NuGet Packages
      run: dotnet restore EncompassApi.xUnit/EncompassApi.xUnit.csproj

    - name: Build Solution
      run: dotnet build -c $env:CONFIGURATION -p:Version=${{ steps.gitversion.outputs.MajorMinorPatch }} -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }} --version-suffix ${{ steps.gitversion.outputs.PreReleaseTag }} EncompassApi.xUnit/EncompassApi.xUnit.csproj

    - name: Nuget Spec
      run: Nuget spec EncompassApi.xUnit
      
    - name: Nuget pack
      run: Nuget pack -IncludeReferencedProjects -Version ${{ variables.versionNumber }} -OutputDirectory EncompassApi.xUnit/bin/Release/netstandard2.0

    - name: Push NuGet Package
      run: dotnet nuget push --no-symbols --skip-duplicates --api-key ${{ secrets.NUGET_API_KEY }} "EncompassApi.xUnit/bin/Release/**/*.nupkg"
